// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.2.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AutomatizacionScoleg.Features.M02Adm_Usuarios
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.2.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("M02 Adm. Usuarios_S03 Usuario")]
    public partial class M02Adm_Usuarios_S03UsuarioFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "M02 Adm. Usuario_S03 Usuario.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("es"), "M02 Adm. Usuarios_S03 Usuario", "\tMacro Proceso Administrador\r\n\tProceso Administrador de usuarios\r\n\tSubProceso Usu" +
                    "ario", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("CP01_Listar Usuario")]
        public virtual void CP01_ListarUsuario()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("CP01_Listar Usuario", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
testRunner.Given("El usuario ingresa a la opcion de menú Listar Usuarios", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 8
testRunner.Then("El sistema despliega una grilla con los registros de usuarios existentes en el si" +
                    "stema", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entonces ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("CP02_Ingresar Usuario")]
        [NUnit.Framework.TestCaseAttribute("17.994.858-3", "NombrePruebaUsuario", "ApellidoPaternoPrueba", "ApellidoMaternoPrueba", "17.994.858-3", "123456789", "123456789", "12345678", "mailprueba@mail.com", "SUCURSAL TEMUCO", "Experto", new string[] {
                "source:M02_Adm.Usuarios.xlsx:INGRESAR.USUARIO"}, Category="source:M02_Adm.Usuarios.xlsx:INGRESAR.USUARIO")]
        public virtual void CP02_IngresarUsuario(string rutUsuario, string nombre, string apellidoPaterno, string apellidoMaterno, string username, string password, string confirmPassword, string telefono, string email, string sucursal, string perfil, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("CP02_Ingresar Usuario", exampleTags);
#line 10
this.ScenarioSetup(scenarioInfo);
#line 11
 testRunner.Given("El usuario ingresa a la opción de menú Ingresar Usuarios", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 12
 testRunner.And(string.Format("El sistema despliega el formulario para ingresar rut de usuario {0}", rutUsuario), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Y ");
#line 13
 testRunner.When(string.Format("El usuario ingresa los datos necesarios para ingresar un nuevo usuario: Nombre {0" +
                        "}, Apellido Paterno {1}, Apellido Materno {2}, Username {3}, Password {4}, Confi" +
                        "rmar Password {5}, Telefono {6}, Email {7},selecciona Sucursal {8} y selecciona " +
                        "Perfil {9}", nombre, apellidoPaterno, apellidoMaterno, username, password, confirmPassword, telefono, email, sucursal, perfil), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Cuando ");
#line 14
 testRunner.And("El usuario pulsa el botón Registrar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Y ");
#line 15
 testRunner.And("El usuario confirma el ingreso del registro", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Y ");
#line 16
 testRunner.Then(string.Format("El sistema despliega en la grilla el registro ingresado con el rut {0}", rutUsuario), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entonces ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("CP03_Editar Usuario")]
        [NUnit.Framework.TestCaseAttribute("TestGrupoAut1", "Informes Operativos", "", "", "", "", "", "", "", "", "", new string[] {
                "source:M02_Adm.Usuarios.xlsx:EDITAR.USUARIO"}, Category="source:M02_Adm.Usuarios.xlsx:EDITAR.USUARIO")]
        public virtual void CP03_EditarUsuario(string rutUsuario, string nombre, string apellidoPaterno, string apellidoMaterno, string username, string password, string confirmPassword, string telefono, string email, string sucursal, string perfil, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("CP03_Editar Usuario", exampleTags);
#line 22
this.ScenarioSetup(scenarioInfo);
#line 23
 testRunner.Given("El usuario ingresa a la opción de menú Listar Usuarios", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 24
 testRunner.And(string.Format("El usuario pulsa el botón Detalle para el registro el rut {0}", rutUsuario), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Y ");
#line 25
 testRunner.When(string.Format("El usuario reemplaza los datos del usuario con la siguiente información: Nombre {" +
                        "0}, Apellido Paterno {1}, Apellido Materno {2}, Username {3}, Password {4}, Conf" +
                        "irmar Password {5}, Telefono {6}, Email {7},selecciona Sucursal {8} y selecciona" +
                        " Perfil {9}", nombre, apellidoPaterno, apellidoMaterno, username, password, confirmPassword, telefono, email, sucursal, perfil), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Cuando ");
#line 26
 testRunner.And("El usuario pulsa el botón Editar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Y ");
#line 27
 testRunner.And("El usuario confirma a edición del registro", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Y ");
#line 28
 testRunner.Then(string.Format("El sistema despliega en la grilla el registro modificado con el rut {0}", rutUsuario), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entonces ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion

