// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.2.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AutomatizacionScoleg.Features.M01Transversal
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.2.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("M01 Transversal_S01 Sesion")]
    public partial class M01Transversal_S01SesionFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "M01 Transversal_S01 Sesion.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("es"), "M01 Transversal_S01 Sesion", "\tMacro Proceso Transversal\r\n\tProceso Acceso\r\n\tSubProceso Sesión", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("CP02_Cerrar Sesión")]
        public virtual void CP02_CerrarSesion()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("CP02_Cerrar Sesión", ((string[])(null)));
#line 16
this.ScenarioSetup(scenarioInfo);
#line 17
 testRunner.Given("El usuario pulsa el botón Cerrar Sesión", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 18
 testRunner.When("El usuario confirma el cierre de sesión", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Cuando ");
#line 19
 testRunner.Then("El sistema despliega formulario de inicio de sesión", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entonces ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("CP01_Iniciar Sesión")]
        [NUnit.Framework.TestCaseAttribute("19.403.866-6", "34567890", new string[] {
                "source:M01_Transversal.xlsx:INICIAR.SESION"}, Category="source:M01_Transversal.xlsx:INICIAR.SESION")]
        [NUnit.Framework.TestCaseAttribute("23.423.423-4", "12345678", new string[] {
                "source:M01_Transversal.xlsx:INICIAR.SESION"}, Category="source:M01_Transversal.xlsx:INICIAR.SESION")]
        public virtual void CP01_IniciarSesion(string rutUsuario, string password, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("CP01_Iniciar Sesión", exampleTags);
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
 testRunner.Given("El sistema despliega formulario de inicio de sesión", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 8
 testRunner.When(string.Format("El usuario ingresa el Rut {0} y Password {1}", rutUsuario, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Cuando ");
#line 9
 testRunner.And("El usuario pulsa el botón Log In", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Y ");
#line 10
 testRunner.Then("El sistema despliega página principal del sitio Legal Partner", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entonces ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
